### ISSUE TITLE
Cannot connect to any server on alias: default with Uris: ('')

### ISSUE THREAD

**Issue by AhmedElmaghraby207** [neo4j-php/neo4j-php-client#164]
I'm using neo4j with "laudis/neo4j-php-client": "^2.8" package
And this error occurred suddenly with error message:
Cannot connect to any server on alias: default with Uris: ('')
And here is my code to connect to neo4j DB Aura using bolt

```
public static function RunStatement($statement)
{
    if (Config::get('neo4j_connection')) {
        $client = Config::get('neo4j_connection');
    } else {
        try {
            $client = self::createClientBuilder();
        } catch (Exception $e) {
            captureMessage($e->getMessage());
            $client = self::createClientBuilder();
        }
    }

    try {
        return self::execute($client, $statement);
    } catch (Exception $e) {
        captureMessage($e->getMessage());
        return self::execute($client, $statement);
    }
}
```
```
private static function createClientBuilder(): ClientInterface
    {
        $auth = Authenticate::basic(env('DB_USERNAME_NEO4J'), env('DB_PASSWORD_NEO4J'));
        $client = ClientBuilder::create()
            ->withDriver('default', env('DB_BOLT_NEO4J'), $auth)
            ->withDefaultTransactionConfiguration(TransactionConfiguration::default()
                ->withTimeout(300)
            )
            ->build();

        Config::set('neo4j_connection', $client);
        return $client;
    }
```
```
 private static function execute($client, $statement)
 {
     return $client->writeTransaction(static function (TransactionInterface $tsx) use ($statement) {
         return $tsx->run($statement->getText());
     });
 }
```

Please advise to solve this issue @transistive

**Comment by transistive** [comment]
Hello @AhmedElmaghraby207, I just responded [here](https://community.neo4j.com/t5/drivers-stacks/cannot-connect-to-any-server-on-alias-default-with-uris/m-p/64491#M5240), but will for good measure copy my response here as well:

> Can you please confirm the 'DB_BOLT_NEO4J', 'DB_USERNAME_NEO4J' and 'DB_PASSWORD_NEO4J' is correctly loaded into the environment? I have a feeling these are just null or an empty string.

**Comment by qury** [comment]
I have a similar error when using 'bolt+ssc', however if i use 'bolt' it works fine.

![image](https://user-images.githubusercontent.com/1764676/215549650-8ed10d7b-cb55-4533-a828-2d6e9a9daab7.png)

I'm using docker:

```
version: '2'

services:
  neo4j:
    image: neo4j:5.3.0-community
    container_name: neo4j
    ports:      
      - 7474:7474
      - 7687:7687 
      - 6362:6362
    environment:
      - NEO4J_AUTH=neo4j/testPassword
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_server_backup_enabled=true
      - NEO4J_server_backup_listen__address=0.0.0.0:6362
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true 
      - NEO4J_server_memory_heap_initial__size=3600MB
      - NEO4J_server_memory_heap_max__size=3600MB
      - NEO4J_server_memory_pagecache_size=2GB
      - NEO4J_server_jvm_additional=-XX:+ExitOnOutOfMemoryError
      - NEO4J_PLUGINS='["apoc-core"]'
      # https://neo4j.com/docs/operations-manual/current/security/ssl-framework/#ssl-bolt-connect
      - NEO4J_server.bolt.enabled=true
      - NEO4J_dbms.ssl.policy.bolt.enabled=true
      - NEO4J_dbms.ssl.policy.bolt.base_directory=/var/lib/neo4j/certificates/bolt
      - NEO4J_dbms.ssl.policy.bolt.private_key=private.key
      - NEO4J_dbms.ssl.policy.bolt.public_certificate=public.crt
      - NEO4J_dbms.ssl.policy.bolt.client_auth=NONE
      - NEO4J_server.bolt.tls_level=REQUIRED
    volumes:
      - neo4j_v5_data:/data
      - /home/DATA/neo4j/docker/certificates:/var/lib/neo4j/certificates
      - /home/DATA/neo4j/backups:/backups
      - /home/DATA/neo4j/logs:/logs
      - /home/DATA/neo4j/plugins:/plugins
      - /home/DATA/neo4j/import:/var/lib/neo4j/import

volumes:
  neo4j_v5_data:
    external: true




```
